server:  port: 8082
logging:
  level:
    root: trace    '[org.apache.tomcat]': INFO    '[org.apache.tomcat.util.net]': WARNspring:  main:    banner-mode: console  banner:    location: classpath:custom-banner.txt    